export const pets = [
  {
    nome: "Totó",
    raca: "cachorro",
    idade: "3 anos",
    cor: "caramelo",
    dono: "Fulano da Silva",
    endereco: "N° 31, bloco C, torre A",
    telefone: "99 99999-9999",
    imagem: "pet1.jpg",
  },
  {
    nome: "Mel",
    raca: "gato",
    idade: "2 anos",
    cor: "branco e preto",
    dono: "Maria Souza",
    endereco: "N° 15, bloco A, torre B",
    telefone: "98 88888-8888",
    imagem: "pet13.jpg",
  },
  {
    nome: "Yoshi",
    raca: "pássaro",
    idade: "1 ano",
    cor: "verde",
    dono: "Ana Santos",
    endereco: "N° 45, bloco D, torre A",
    telefone: "97 77777-7777",
    imagem: "pet15.jpg",
  },
  {
    nome: "Toby",
    raca: "cachorro",
    idade: "5 anos",
    cor: "preto",
    dono: "Carlos Lima",
    endereco: "N° 10, bloco F, torre C",
    telefone: "96 66666-6666",
    imagem: "pet18.jpg",
  },
  {
    nome: "Lili",
    raca: "gato",
    idade: "4 anos",
    cor: "cinza",
    dono: "Fernanda Alves",
    endereco: "N° 21, bloco B, torre A",
    telefone: "95 55555-5555",
    imagem: "pet17.jpg",
  },
];
